
export const SEND_USERNAME_PASSWORD = 'SEND_USERNAME_PASSWORD'
export const LOG_USER_OUT = 'LOG_USER_OUT'
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'

export const OPEN_MENU = 'OPEN_MENU'
export const CLOSE_MENU = 'CLOSE_MENU'
